### ISSUE TITLE
Method name prefix dct_ confuses static analyzer

### ISSUE THREAD

**Issue by postmechanical** [danielctull/DCTCoreData#5]
For example:

DCTCoreData/NSFetchRequest+DCTExtras.m:44:2: warning: Object sent -autorelease too many times
         return [[[self alloc] dct_initWithEntity:entity] autorelease];
         ^
DCTCoreData/NSFetchRequest+DCTExtras.m:50:2: warning: Object sent -autorelease too many times
         return [[[self alloc] dct_initWithEntity:entity
         ^
DCTCoreData/NSFetchRequest+DCTExtras.m:57:2: warning: Object sent -autorelease too many times
         return [[[self alloc] dct_initWithEntity:entity
         ^
DCTCoreData/NSFetchRequest+DCTExtras.m:65:2: warning: Object sent -autorelease too many times
         return [[[self alloc] dct_initWithEntity:entity
         ^
DCTCoreData/NSFetchRequest+DCTExtras.m:75:2: warning: Object sent -autorelease too many times
         return [[[self alloc] dct_initWithEntity:entity

Even with ARC will these names not also cause problems for the compiler?

**Comment by danielctull** [comment]
They will be fine with ARC, but that's because it will treat them as returning an autoreleased object. I have a fix for this though. Bear in mind that currently DCTCoreData 2.0 only supports ARC out of the box.
